version: '3'

services:
  demo:
    build: demo-app
    ports:
    - "8080:8080"
    
  cadvisor:
      image: google/cadvisor:latest
      container_name: cadvisor
      volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  
  prometheus:
    build: prometheus
    ports:
    - "9090:9090"
